
CREATE DATABASE emailmgr ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';


CREATE TABLE domain (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	spooldir char(40) NOT NULL UNIQUE,
	created TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT TIMESTAMP WITH TIME ZONE 'January 1, 4713 BC',
	modified TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT TIMESTAMP WITH TIME ZONE 'January 1, 4713 BC',
	active BOOLEAN NOT NULL DEFAULT TRUE,
	public BOOLEAN NOT NULL DEFAULT TRUE,
	ad_guid BYTEA DEFAULT NULL UNIQUE,
	ad_sync_enabled BOOLEAN NOT NULL DEFAULT TRUE
	);


CREATE TABLE account (
	id SERIAL PRIMARY KEY,
	domain_id INTEGER,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(64) NOT NULL DEFAULT '',
	password_enabled BOOLEAN NOT NULL DEFAULT FALSE,
	fullname VARCHAR(255) DEFAULT NULL,
	spooldir char(40) NOT NULL UNIQUE,
	created TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT TIMESTAMP WITH TIME ZONE 'January 1, 4713 BC',
	modified TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT TIMESTAMP WITH TIME ZONE 'January 1, 4713 BC',
	accessed TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT TIMESTAMP WITH TIME ZONE 'January 1, 4713 BC',
	active BOOLEAN NOT NULL DEFAULT TRUE,
	public BOOLEAN NOT NULL DEFAULT TRUE,
	ad_guid BYTEA DEFAULT NULL UNIQUE,
	ad_sync_enabled BOOLEAN NOT NULL DEFAULT TRUE,
	ad_sync_required BOOLEAN NOT NULL DEFAULT FALSE,
	ad_time_changed BYTEA DEFAULT NULL,
	CONSTRAINT name_domain UNIQUE (name, domain_id),
	CONSTRAINT fk_domain_id FOREIGN KEY (domain_id) REFERENCES domain(id)
	);

CREATE INDEX idx_account_fullname ON account(fullname);
CREATE INDEX idx_account_domain_id ON account(domain_id);
